-- Migration 001: giveaway_codes
-- Codes generated by streamer/mods, redeemable once for a fixed USD amount.

CREATE TABLE IF NOT EXISTS giveaway_codes (
    id              BIGSERIAL PRIMARY KEY,
    code            TEXT NOT NULL UNIQUE,
    amount_usd      NUMERIC(12, 2) NOT NULL CHECK (amount_usd > 0),
    created_by      TEXT NOT NULL,              -- Discord user ID of streamer/mod
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL,
    status          TEXT NOT NULL DEFAULT 'unused'
                        CHECK (status IN ('unused', 'redeemed', 'expired', 'voided')),
    voided_by       TEXT,                        -- who voided it, if applicable
    voided_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_giveaway_codes_status ON giveaway_codes(status);
CREATE INDEX IF NOT EXISTS idx_giveaway_codes_code ON giveaway_codes(code);
